version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nt_postgres
    restart: always
    environment:
      POSTGRES_USER: quant_user
      POSTGRES_PASSWORD: quant_password_123
      POSTGRES_DB: national_team_db
    ports:
      - "5432:5432"
    volumes:
      - ./storage/db_data:/var/lib/postgresql/data
      - ./database_onlyTables.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quant_net

networks:
  quant_net:
    driver: bridge
